# Numpy : Sorting Arrays


## Selection Sort

- Useful for its simplicity, but is much too slow to be useful for larger arrays. 
- For a list of N values, it requires N loops, each of which does on the order of N comparisons to find the swap value.
- Selection sort averages O(N^2) 

In [26]:
import numpy as np

arr = [2,9,6,5,7,6]

In [27]:
def selection_sort(arr):
    for i in range(len(arr)):
        swap = i + np.argmin(arr[i:])
        (arr[i],arr[swap]) = (arr[swap], arr[i])
    return arr

In [28]:
selection_sort(arr)

[2, 5, 6, 6, 7, 9]

# Fast Sorting in NumPy

By default np.sort uses an O(NlogN),quicksort algorithm, though mergesort and heapsort are also available. For most applications,the default quicksort is more than sufficient.

In [30]:
x = np.array([4,8,54,8,549,5,6,8,4821,224,56,6,8])
np.sort(x)

array([   4,    5,    6,    6,    8,    8,    8,    8,   54,   56,  224,
        549, 4821])

In [34]:
np.argsort(x)                      #returns indices of sorted elements

array([ 0,  5,  6, 11,  1,  3,  7, 12,  2, 10,  9,  4,  8], dtype=int64)

In [38]:
#multidimensioanl sorting 
m = np.array([[1,5,6,6,8],
             [7,8,9,9,88],
             [8,99,6,7,25],
             [9,0,6,99,12]])
np.sort(m)      #sorts each row

array([[ 1,  5,  6,  6,  8],
       [ 7,  8,  9,  9, 88],
       [ 6,  7,  8, 25, 99],
       [ 0,  6,  9, 12, 99]])

In [39]:
np.sort(m,axis=0) #sorts each column

array([[ 1,  0,  6,  6,  8],
       [ 7,  5,  6,  7, 12],
       [ 8,  8,  6,  9, 25],
       [ 9, 99,  9, 99, 88]])

In [41]:
np.partition(x,5)         #sorts upto specified position and returns rest of the elements in arbitrary order

array([   5,    4,    6,    6,    8,    8,    8,    8,   54,  224,   56,
        549, 4821])