<h1><center>NUMPY </h1>

NumPy (short for Numerical Python) provides
an efficient interface to store and operate on dense data buffers

In [2]:
import numpy as np

In [6]:
#Python is dynamically typed language
x = 4
x = "four"
x

'four'

In [12]:
#list of numbers
my_list = list(range(10))
print(my_list)

#list of strings
my_strings = [str(x) for x in my_list]
print(my_strings)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


In [19]:
#heterogenous list
het_list =  [1,2,"hello", 12.65,['a','c']]
print(type(het_list))
print(type(het_list[0]))

<class 'list'>
<class 'int'>


In [20]:
#Creating Arrays from Python Lists
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr = np.array(het_list)
arr

array([1, 2, 'hello', 12.65, list(['a', 'c'])], dtype=object)

In [24]:
#creating an array of all zeroes 
arr = np.zeros(10, dtype = "int")
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
#array with all ones
arr = np.ones((3,2),dtype = "int")
arr

array([[1, 1],
       [1, 1],
       [1, 1]])

In [33]:
#array with all values same 
np.full(10,55)

array([55, 55, 55, 55, 55, 55, 55, 55, 55, 55])

In [37]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2. arange(start, end, step)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
#create an array of numbers between 0 and 1, into 5 parts
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [43]:
#create an array of random values, between 0 and 1
np.random.random(5)

array([0.70081303, 0.91660381, 0.2138573 , 0.82139486, 0.08765408])

In [46]:
#create an array of random values, between 0 and 1, mean =0 and std deviation = 1
np.random.normal(0,1,5)

array([ 1.03932333, -1.08300724,  0.14764626,  0.44424744,  0.24764665])

In [48]:
#create identity matrix
np.eye(5,dtype="int")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [56]:
#create uninitialsed array. 
np.empty(2)

array([8.83883838e-312, 8.83883838e-312])

## NumPy Array Attributes

In [62]:
np.random.seed(0)         #to ensure it starts with same number every time
arr1 = np.random.randint(10 ,size=1)
arr2 = np.random.randint(10, size=(2,2))
arr3 = np.random.randint(10, size=(3,3,3))
arr3

array([[[9, 3, 5],
        [2, 4, 7],
        [6, 8, 8]],

       [[1, 6, 7],
        [7, 8, 1],
        [5, 9, 8]],

       [[9, 4, 3],
        [0, 3, 5],
        [0, 2, 3]]])

In [68]:
arr2.shape     #shape of the array

(2, 2)

In [67]:
arr2.ndim      #number of dimensions

2

## Accessing Arrays and Subarrays

In [123]:
arr = np.arange(10)
arr

array([10, 12, 14, 16, 18])

In [72]:
arr[5]

5

In [104]:
arr[:5]                          #a[start:stop:step]

array([[8, 4, 3, 7, 5],
       [5, 0, 1, 5, 9],
       [3, 0, 5, 0, 1],
       [2, 4, 2, 0, 3]])

In [105]:
arr[5:]

array([], shape=(0, 5), dtype=int32)

In [106]:
arr[::2]

array([[8, 4, 3, 7, 5],
       [3, 0, 5, 0, 1]])

In [107]:
arr[::]

array([[8, 4, 3, 7, 5],
       [5, 0, 1, 5, 9],
       [3, 0, 5, 0, 1],
       [2, 4, 2, 0, 3]])

In [108]:
arr[::-1]

array([[2, 4, 2, 0, 3],
       [3, 0, 5, 0, 1],
       [5, 0, 1, 5, 9],
       [8, 4, 3, 7, 5]])

### Multidimensional Subarrays

In [114]:
arr = np.random.randint(10,size=(4,5))
arr

array([[4, 6, 8, 2, 3],
       [0, 0, 6, 0, 6],
       [3, 3, 8, 8, 8],
       [2, 3, 2, 0, 8]])

In [115]:
arr[0][4]

3

In [116]:
arr[:2, :3]

array([[4, 6, 8],
       [0, 0, 6]])

In [117]:
arr[1:3:1, ::2]

array([[0, 6, 6],
       [3, 8, 8]])

In [118]:
arr[::-1, ::-1]

array([[8, 0, 2, 3, 2],
       [8, 8, 8, 3, 3],
       [6, 0, 6, 0, 0],
       [3, 2, 8, 6, 4]])

In [120]:
x =  arr.copy()
x

array([[4, 6, 8, 2, 3],
       [0, 0, 6, 0, 6],
       [3, 3, 8, 8, 8],
       [2, 3, 2, 0, 8]])