<h1><center>NUMPY </h1>

NumPy (short for Numerical Python) provides
an efficient interface to store and operate on dense data buffers

In [9]:
import numpy as np

In [10]:
#Python is dynamically typed language
x = 4
x = "four"
x

'four'

In [11]:
#list of numbers
my_list = list(range(10))
print(my_list)

#list of strings
my_strings = [str(x) for x in my_list]
print(my_strings)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


In [12]:
#heterogenous list
het_list =  [1,2,"hello", 12.65,['a','c']]
print(type(het_list))
print(type(het_list[0]))

<class 'list'>
<class 'int'>


In [13]:
#Creating Arrays from Python Lists
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr = np.array(het_list)
arr

array([1, 2, 'hello', 12.65, list(['a', 'c'])], dtype=object)

In [15]:
#creating an array of all zeroes 
arr = np.zeros(10, dtype = "int")
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
#array with all ones
arr = np.ones((3,2),dtype = "int")
arr

array([[1, 1],
       [1, 1],
       [1, 1]])

In [18]:
#array with all values same 
np.full(10,55)

array([55, 55, 55, 55, 55, 55, 55, 55, 55, 55])

In [19]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2. arange(start, end, step)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
#create an array of numbers between 0 and 1, into 5 parts
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
#create an array of random values, between 0 and 1
np.random.random(5)

array([0.60002257, 0.85840111, 0.61833003, 0.94962403, 0.09039246])

In [22]:
#create an array of random values, between 0 and 1, mean =0 and std deviation = 1
np.random.normal(0,1,5)

array([ 0.18541832,  0.89816186,  1.57029381, -1.21574969, -0.17516869])

In [23]:
#create identity matrix
np.eye(5,dtype="int")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [24]:
#create uninitialsed array. 
np.empty(2)

array([2.00995441e-309, 3.63277710e+180])

## NumPy Array Attributes

In [25]:
np.random.seed(0)         #to ensure it starts with same number every time
arr1 = np.random.randint(10 ,size=1)
arr2 = np.random.randint(10, size=(2,2))
arr3 = np.random.randint(10, size=(3,3,3))
arr3

array([[[9, 3, 5],
        [2, 4, 7],
        [6, 8, 8]],

       [[1, 6, 7],
        [7, 8, 1],
        [5, 9, 8]],

       [[9, 4, 3],
        [0, 3, 5],
        [0, 2, 3]]])

In [26]:
arr2.shape     #shape of the array

(2, 2)

In [27]:
arr2.ndim      #number of dimensions

2

## Accessing Arrays and Subarrays

In [28]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr[5]

5

In [30]:
arr[:5]                          #a[start:stop:step]

array([0, 1, 2, 3, 4])

In [31]:
arr[5:]

array([5, 6, 7, 8, 9])

In [32]:
arr[::2]

array([0, 2, 4, 6, 8])

In [33]:
arr[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Multidimensional Subarrays

In [35]:
arr = np.random.randint(10,size=(4,5))
arr

array([[8, 1, 3, 3, 3],
       [7, 0, 1, 9, 9],
       [0, 4, 7, 3, 2],
       [7, 2, 0, 0, 4]])

In [36]:
arr[0][4]

3

In [37]:
arr[:2, :3]

array([[8, 1, 3],
       [7, 0, 1]])

In [38]:
arr[1:3:1, ::2]

array([[7, 1, 9],
       [0, 7, 2]])

In [39]:
arr[::-1, ::-1]

array([[4, 0, 0, 2, 7],
       [2, 3, 7, 4, 0],
       [9, 9, 1, 0, 7],
       [3, 3, 3, 1, 8]])

In [40]:
x =  arr.copy()
x

array([[8, 1, 3, 3, 3],
       [7, 0, 1, 9, 9],
       [0, 4, 7, 3, 2],
       [7, 2, 0, 0, 4]])

In [47]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Array Concatenation and Splitting

In [60]:
#concatenate two arrays
ar1 = np.array([1,89,8,9,8])
ar2 = np.array([4,5])
ar3 = np.array([2,3,9])
np.concatenate([ar1,ar2,ar3])

array([ 1, 89,  8,  9,  8,  4,  5,  2,  3,  9])

In [63]:
#conactenating multidimensional arrays
ar1 = np.array([[1,2],[8,9]])
ar2 = np.array([[5,9],[7,3]])
np.concatenate([ar1,ar2])

array([[1, 2],
       [8, 9],
       [5, 9],
       [7, 3]])

In [64]:
np.vstack([ar1,ar2])

array([[1, 2],
       [8, 9],
       [5, 9],
       [7, 3]])

In [65]:
np.hstack([ar1,ar2])

array([[1, 2, 5, 9],
       [8, 9, 7, 3]])

In [68]:
y = np.array([88,88])
np.vstack([ar1,y])

array([[ 1,  2],
       [ 8,  9],
       [88, 88]])

In [75]:
#splitting of arrays
arr = np.arange(10)
np.split(arr,[2,5])         #n split points give n+1 arrays

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [76]:
arr = np.arange(16).reshape((4,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [79]:
np.hsplit(arr,[3])

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]), array([[ 3],
        [ 7],
        [11],
        [15]])]

In [80]:
np.vsplit(arr,[3])

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]

## UFunctions 

For many types of operations, NumPy provides a convenient interface, known as a vectorized operation. Computations using vectorization through ufuncs are nearly always more efficient than their counterpart implemented through Python loops, especially as the arrays grow in size. Any time you see such a loop in a Python script, you should consider whether it can be replaced with a vectorized expression.

In [81]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
#adding 2to every element of arr
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [83]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])