## Aggregate Functions

In [1]:
import numpy as np

In [2]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [5]:
s = np.sum(arr)
t = np.add.reduce(arr)
s,t

(300, 300)

In [20]:
%timeit sum(arr)

4.68 µs ± 847 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [21]:
%timeit np.sum(arr)

4.79 µs ± 748 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Multidimensional aggregate

In [26]:
marr = np.random.random((3,4))
marr

array([[0.36253476, 0.61913572, 0.08957963, 0.18641726],
       [0.91659695, 0.75701646, 0.80973169, 0.26198488],
       [0.89350193, 0.60819568, 0.5442278 , 0.05328423]])

In [28]:
np.sum(marr)

6.102207004367985

In [30]:
#row wise sum
np.sum(marr,axis=1)

array([1.25766738, 2.74532998, 2.09920965])

In [31]:
#column wise sum
np.sum(marr,axis=0)

array([2.17263364, 1.98434786, 1.44353913, 0.50168637])

In [33]:
marr.max(axis=1)     #in each row

array([0.61913572, 0.91659695, 0.89350193])